
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joyeria_la_perla?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootmysql
  jpa:
    hibernate:
      ddl-auto: update