spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lasperlas
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect