spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:lasPerlas
    username: admin
    password: admin
  h2:
    console:
      enabled: true